services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    restart: unless-stopped
    networks:
      - inception_network
    env_file:
      - .env

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html
      - ../secrets:/var/secrets:ro
    restart: unless-stopped
    networks:
      - inception_network
    env_file:
      - .env

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    volumes:
      - mariadb:/var/lib/mysql
      - ../secrets:/var/secrets:ro
    restart: unless-stopped
    networks:
      - inception_network
    env_file:
      - .env

# volumes:

volumes:
  mariadb:
    name: mariadb

  wordpress:
    name: wordpress
  # wordpress:
  #   driver: local
  #   driver_opts:
  #     type: none
  #     o: bind
  #     device: ${HOME:-${USER}}/data/wordpress
  # mariadb:
  #   driver: local
  #   driver_opts:
  #     type: none
  #     o: bind
  #     device: ${HOME:-${USER}}/data/mariadb

# networks:
networks:
  inception_network:
    driver: bridge